import { mkdtempSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { expect,it } from 'vitest';
import { openOwnedStore } from '../../src/db';
import { canonicalDigest } from '../../src/contracts/common';
import type { ApplicationCommand } from '../../src/db/application';
it('commits resources, receipts, comments and acceptance with restart-safe exact retries',async()=>{
 const dir=mkdtempSync(join(realpathSync(tmpdir()),'agentflow-p02-'));
 let owned=await openOwnedStore(dir);
 const send=(command:ApplicationCommand,path:string,key=randomUUID())=>owned.store.command(command,{principal:'operator',method:'POST',path,key,digest:canonicalDigest(command),now:1000});
 const p=send({kind:'project.create',input:{name:'Synthetic project'}},'/api/v1/projects');
 const projectId=(p.body.data as {id:string}).id;
 const command:ApplicationCommand={kind:'task.create',input:{projectId,title:'Synthetic task'}};
 const key=randomUUID(); const created=send(command,'/api/v1/tasks',key); const taskId=(created.body.data as {id:string}).id;
 expect(send(command,'/api/v1/tasks',key)).toEqual(created);
 expect(()=>send({...command,input:{projectId,title:'changed'}},'/api/v1/tasks',key)).toThrow('idempotency_conflict');
 send({kind:'task.patch',id:taskId,input:{expectedVersion:1,status:'review'}},'/api/v1/tasks/'+taskId);
 const accepted=send({kind:'task.complete',id:taskId,input:{expectedVersion:2,evidenceNote:'Synthetic acceptance fixture'}},'/api/v1/tasks/'+taskId+'/complete');
 send({kind:'comment.create',id:taskId,input:{text:'immutable context'}},'/api/v1/tasks/'+taskId+'/comments');
 const detail=owned.store.snapshot({kind:'task',id:taskId,input:{history:'both',historyLimit:50}},1000);
 expect(detail.body.data).toMatchObject({task:{version:3,workRevision:1,status:'completed'},currentCompletion:accepted.body.data});
 expect(()=>send({kind:'task.patch',id:taskId,input:{expectedVersion:2,title:'lost edit'}},'/api/v1/tasks/'+taskId)).toThrow('version_conflict');
 owned.close(); owned=await openOwnedStore(dir);
 expect(send(command,'/api/v1/tasks',key)).toEqual(created);
 expect(owned.store.integrity().integrity).toBe('ok'); owned.close();
});
