"use client";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useRead,useWorkspace,QueryFeedback } from "../client/provider";
import { settingsResponse } from "../contracts/responses";
import { settingsPatch } from "../contracts/settings";
import { freezeCommand } from "../client/commands";
import { ApiError } from "../client/api";
import SignOut from "../app/sign-out";
export function Settings(){const query=useRead("/settings",settingsResponse);const {api,pair}=useWorkspace();const cache=useQueryClient();const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const data=query.data?.data;return <><h1>Settings</h1><QueryFeedback error={query.error} loading={query.isPending} retry={()=>void query.refetch()}/>{data&&<><section className="settings-section"><h2>Local day and timezone</h2><p>Overview uses this timezone to count today’s work.</p><form onSubmit={async e=>{e.preventDefault();const input=settingsPatch.safeParse({expectedVersion:data.version,timezone:new FormData(e.currentTarget).get("timezone")});if(!input.success){setMessage("Enter a valid IANA timezone, such as Europe/London or UTC.");return;}setBusy(true);try{await api.command(freezeCommand("/settings","PATCH",input.data));await cache.invalidateQueries();setMessage("Timezone saved.");}catch(error){if(error instanceof ApiError&&error.status===401)pair();setMessage(error instanceof ApiError&&error.status===409?"Timezone changed in another browser. Review the current setting before saving.":"Could not save timezone. Your input is retained.");void query.refetch();}finally{setBusy(false);}}}><label>Timezone<input name="timezone" required defaultValue={data.timezone} key={data.version}/></label><button className="primary" disabled={busy}>Save timezone</button><p role="status">{message}</p></form></section><section className="settings-section"><h2>Storage on this machine</h2><dl><dt>Data location</dt><dd className="break-word">{data.dataLocation}</dd><dt>Observed storage</dt><dd>{data.storageBytes.toLocaleString()} bytes</dd></dl><p>This size is observational. Stop AgentFlow before restoring a backup. Use the local backup command described in the setup instructions.</p></section><section className="settings-section"><h2>Browser pairing</h2><p>This browser is paired to the local workspace.</p><SignOut/></section></>}</>;}
